Repository UAL-RE/redata-commons, pull requests merged in 2021-04, with the labels that each got.

#10 Add logger module
  CHANGELOG.md
  README.md
  docs/requirements.txt
  docs/source/execution.rst
  docs/source/index.rst
  docs/source/redata.commons.rst
  redata/__init__.py
  redata/commons/__init__.py
  redata/commons/logger.py
  requirements.txt
  setup.py
  tests/test_logger.py
Labels: CI/CD, documentation, enhancement

#12 Update README.md for Sphinx documentation
  CHANGELOG.md
  README.md
  redata/__init__.py
  setup.py
Labels: documentation

#14 Bug: LogCommons has hardcoded pieces
  CHANGELOG.md
  redata/__init__.py
  redata/commons/logger.py
  setup.py
Labels: bug
